site_name: Portfolio - Nick Wheeler

theme: 
  name: material
  
nav:
  - Home: index.md
  - API Docs:
      - Overview: api/index.md
      - Reference: api/reference.md
      - Tutorial: api/tutorial.md
  - CI/CD:
      - GitHub Actions Guide: cicd/github-actions.md
  - DevOps Tools:
      - Terraform Overview: devops/terraform.md
  - About: about.md
